.github/workflows/update_weather.yml

name: Update weather feed

on:
  schedule:
    - cron: "15 * * * *"   # every hour at :15 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run fetcher
        run: python fetch_weather.py

      - name: Commit weather.json (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.json
          git diff --cached --quiet || git commit -m "Update weather feed"
          git push
